#include <stdio.h> 
unsigned char X[200] = {
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAA”
};
unsigned char Y[200] = {
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
“AAAAAAAAAAAAAAAAAAA”
};
int main()
{
for (int i = 0; i < 200; i++) {
 if (X[i] == Y[i]) {
          printf("X[i] = %.2x, Y[i] = %.2x\n",X[i],Y[i]);
          printf("Running benign code..\n");
          return 0;
   }
  printf("X[i] = %.2x, Y[i] = %.2x\n",X[i],Y[i]);
  printf("Running malicious code...\n");
 } 
 return 0;
}
